[package]
edition = "2021"
name = "luluu"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[dependencies]
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
embedded-hal = { workspace = true }

defmt = { workspace = true }
defmt-rtt = { workspace = true }
panic-probe = { workspace = true, features = ["print-defmt"] }

luluu-bsp = { path = "../luluu-bsp" }
embedded-graphics = { workspace = true }
embedded-sdmmc = { workspace = true }
mipidsi = "0.7.1"
display-interface = "0.4.1"
fugit = { version = "0.3.7" }
display-interface-spi = "0.4.1"
tinygif = "0.0.4"
